spring:
  application:
    name: user-service
  cloud:
    config:
      failFast: true
      retry:
        initialInterval: 1000
        maxInterval: 60000
        maxAttempts: 8
        multiplier: 2

logging:
  level:
    org.springframework.retry: DEBUG
    org.springframework.cloud.config: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: 'env'

---
spring:
  config:
    activate:
        on-profile: local
    import: configserver:http://localhost:8888
